app = "math-phtx3a"
primary_region = "cdg"

[deploy]
release_command = "sh -c 'python manage.py migrate && python manage.py seed_data'"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_000
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512
