# Generated by Django 5.2.8 on 2026-01-29 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Specific configuration for this tool for this grade')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.grade')),
            ],
            options={
                'verbose_name': 'Grade Tool Configuration',
                'verbose_name_plural': 'Grade Tool Configurations',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('tool_type', models.CharField(choices=[('CALC', 'Calculator'), ('SOLVER', 'Equation Solver'), ('GEO', 'Geometry'), ('GRAPH', 'Graphing'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('icon_name', models.CharField(help_text='CSS class or filename for icon', max_length=50)),
                ('grades', models.ManyToManyField(related_name='tools', through='tools.GradeTool', to='grades.grade')),
            ],
        ),
        migrations.AddField(
            model_name='gradetool',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool'),
        ),
        migrations.AlterUniqueTogether(
            name='gradetool',
            unique_together={('grade', 'tool')},
        ),
    ]
