# Generated by Django 5.2.8 on 2026-01-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_type',
            field=models.CharField(choices=[('CALC', 'Calculator'), ('SOLVER', 'Equation Solver'), ('GEO', 'Geometry'), ('GRAPH', 'Graphing'), ('UNIT', 'Unit Converter'), ('MATRIX', 'Matrix Calculator'), ('PROB', 'Probability Simulator'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
